# Generated by Django 3.1.7 on 2022-01-16 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20211027_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='AddToRentHouse',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Approved', 'Approved'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
    ]
